#!/bin/sh
commit_msg=$(cat "$1")
pattern="^(feat|fix|docs|style|refactor|test|chore|task|build|ci|perf|revert): .+"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "Invalid commit message format."
  echo "Expected: <type>: <description>"
  echo "Types: feat, fix, docs, style, refactor, test, chore, task, build, ci, perf, revert"
  echo "Example: task: add unittest"
  exit 1
fi
