#!/bin/sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Use the Node version specified in .nvmrc
nvm use

# Run linting to ensure code quality before committing
npm run lint

# Run type checking before committing
npm run typecheck
